### ISSUE TITLE
flake8-colors breaks `--format` option

### ISSUE THREAD

**Issue by asottile** [and3rson/flake8-colors#12]
```
$ flake8 '--format=%(code)s' - <<< 'import os'
D100
F401
$ flake8 '--format=%(code)s' - <<< 'import os' | cat
stdin:1:1: D100 Missing docstring in public module
stdin:1:1: F401 'os' imported but unused
```

it's resetting the format back to `default`

**Comment by KTibow** [comment]
Could you clarify? Are you sure your formatting is right?

**Comment by asottile** [comment]
yes. I am the flake8 maintainer

**Comment by KTibow** [comment]
I mean use a bit more proper grammar, elaborate, try some troubleshooting.

**Comment by Senpos** [comment]
Hey @and3rson!

I see, that [this commit ](https://github.com/and3rson/flake8-colors/commit/59687c711be22e94a2cd45526a884f4964403ffe)partially fixes the bug, but the issue still remains if you run flake8 with `--color=never` option:
```bash
$ flake8 '--format=%(code)s' - <<< 'import os' --color never | cat
stdin:1:1: F401 'os' imported but unused
```

Changing the color behavior should not impact user-provided formatting.

There are two options here:
1. if colors are disabled, don't substitute `${}` tags and pass them into the output just as a normal text
2. if colors are disabled, just strip out `${...}` tags

I like the option 2 more.

Here's how it can be possibly achieved:
```python
@classmethod
def parse_options(cls, options):
    if options.color == 'always':
        colorized = True
    elif options.color == 'never':
        colorized = False
    else:  # options.color == 'auto'
        # Only use color formatting if invoked interactively
        colorized = sys.stdout.isatty()
        
    replace = cls._replace if colorized else ""
    options.format = sub(r'\$\{([\w]+)\}', replace, options.format)
```

Output:
```bash
$ flake8 '--format=%(code)s' - <<< 'import os' --color never | cat
F401
```

**Comment by JulianVolodia** [comment]
he removed it
https://gitlab.com/pycqa/flake8/-/merge_requests/460

**Comment by ThiefMaster** [comment]
Could this please be fixed? :/ I just wasted over an our trying to figure out why vscode was no longer showing flake8 issues, until I discovered that stdout being a tty caused it (microsoft/vscode-python#14776). Just making the color format return nothing when colors are disabled would already be enough.

**Comment by ThiefMaster** [comment]
I sent a PR to fix this; a fixed release would be appreciated :)

**Comment by and3rson** [comment]
Hi everyone! Unfortunately I'm not able to dedicate this project as much time as necessary, however since this little lib is still being used, I'm open to granting write access to this repo and/or transferring it to those willing to maintain it.

**Comment by ThiefMaster** [comment]
if you give me write access and publish rights on pypi (same username) i can help making at least a new release fixing this problem.

(and i hope my GitHub account has enough professional activity and references to be considered trustworthy ;))

**Comment by zaccrites-intel** [comment]
Has any progress been made on this? It is still an issue.

**Comment by asottile** [comment]
flake8 has landed with native color support
