### ISSUE TITLE
warning using recommended format

### ISSUE THREAD

**Issue by tekumara** [and3rson/flake8-colors#9]
I'm using the example `format` from README.md in .flake8:

```
format = ${cyan}%(path)s${reset}:${yellow_bold}%(row)d${reset}:${green_bold}%(col)d${reset}: ${red_bold}%(code)s${reset} %(text)s
```

`flake --verbose` warns:

```
flake8.main.application   MainProcess    204 WARNING  "%(path)s:%(row)d:%(col)d: %(code)s %(text)s" is an unknown formatter. Falling back to default.
```

**Comment by KTibow** [comment]
This is a problem made by flake8, not flake8-colors. If you uninstall this plugin, and provide a custom format string such as `Line %(row)d %(code)s Error %(text)s`, you still get that error. Consider closing?
